export interface Thumbnail {
  quality?: string;
  url: string;
  width: number;
  height: number;
}

export interface VideoItem {
  type: 'video' | 'shortVideo';
  title: string;
  videoId: string;
  author: string;
  authorId: string;
  authorUrl?: string;
  authorVerified?: boolean;
  authorThumbnails?: Thumbnail[];
  videoThumbnails?: Thumbnail[];
  description?: string;
  descriptionHtml?: string;
  viewCount?: number;
  viewCountText?: string;
  published?: number;
  publishedText?: string;
  lengthSeconds: number;
  liveNow?: boolean;
  premium?: boolean;
  isUpcoming?: boolean;
  premiereTimestamp?: number;
  isNew?: boolean;
  is4k?: boolean;
  hasCaptions?: boolean;
  /** present for playlist items */
  index?: number;
  indexId?: string;
}

export interface ChannelItem {
  type: 'channel';
  author: string;
  authorId: string;
  authorUrl?: string;
  authorVerified?: boolean;
  authorThumbnails: Thumbnail[];
  autoGenerated?: boolean;
  subCount: number;
  videoCount: number;
  channelHandle?: string;
  description?: string;
  descriptionHtml?: string;
}

export interface PlaylistItem {
  type: 'playlist';
  title: string;
  playlistId: string;
  playlistThumbnail?: string;
  author: string;
  authorId?: string;
  authorUrl?: string;
  authorVerified?: boolean;
  videoCount: number;
  videos?: { title: string; videoId: string; lengthSeconds: number; videoThumbnails?: Thumbnail[] }[];
}

export interface HashtagItem {
  type: 'hashtag';
  title: string;
  url: string;
  channelCount: number;
  videoCount: number;
}

export type SearchItem = VideoItem | ChannelItem | PlaylistItem | HashtagItem;

export interface RecommendedVideo {
  videoId: string;
  title: string;
  videoThumbnails?: Thumbnail[];
  author: string;
  authorUrl?: string;
  authorId: string;
  authorVerified?: boolean;
  authorThumbnails?: Thumbnail[];
  lengthSeconds: number;
  viewCountText?: string;
  viewCount?: number;
  published?: string;
  publishedText?: string;
}

export interface AdaptiveFormat {
  init?: string;
  index?: string;
  bitrate: string;
  url: string;
  itag: string;
  type: string;
  clen?: string;
  fps?: number;
  size?: string;
  resolution?: string;
  qualityLabel?: string;
  audioQuality?: string;
  audioSampleRate?: number;
  audioChannels?: number;
}

export interface FormatStream {
  url: string;
  itag: string;
  type: string;
  quality: string;
  fps?: number;
  size?: string;
  resolution?: string;
  qualityLabel?: string;
}

export interface Caption {
  label: string;
  language_code: string;
  url: string;
}

export interface Storyboard {
  url: string;
  templateUrl: string;
  width: number;
  height: number;
  count: number;
  interval: number;
  storyboardWidth: number;
  storyboardHeight: number;
  storyboardCount: number;
}

export interface VideoDetails {
  type: 'video';
  title: string;
  videoId: string;
  videoThumbnails: Thumbnail[];
  storyboards: Storyboard[];
  description: string;
  descriptionHtml: string;
  published: number;
  publishedText: string;
  keywords: string[];
  viewCount: number;
  likeCount: number;
  dislikeCount: number;
  paid: boolean;
  premium: boolean;
  isFamilyFriendly: boolean;
  genre: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified: boolean;
  authorThumbnails: Thumbnail[];
  subCountText: string;
  lengthSeconds: number;
  allowRatings: boolean;
  isListed: boolean;
  liveNow: boolean;
  isPostLiveDvr?: boolean;
  isUpcoming: boolean;
  premiereTimestamp?: number;
  dashUrl: string;
  hlsUrl?: string;
  adaptiveFormats: AdaptiveFormat[];
  formatStreams: FormatStream[];
  captions: Caption[];
  recommendedVideos: RecommendedVideo[];
}

export interface Comment {
  authorId: string;
  authorUrl: string;
  author: string;
  verified?: boolean;
  authorThumbnails?: Thumbnail[];
  authorThumbnail?: string;
  authorIsChannelOwner: boolean;
  isSponsor?: boolean;
  likeCount: number;
  isPinned?: boolean;
  isEdited: boolean;
  commentId: string;
  content: string;
  contentHtml: string;
  published: number;
  publishedText: string;
  creatorHeart?: { creatorThumbnail: string; creatorName: string };
  replies?: { replyCount: number; continuation: string };
}

export interface CommentsResponse {
  commentCount?: number;
  videoId: string;
  comments: Comment[];
  continuation?: string;
}

export interface ChannelDetails {
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified?: boolean;
  authorBanners: Thumbnail[];
  authorThumbnails: Thumbnail[];
  subCount: number;
  totalViews: number;
  joined: number;
  autoGenerated: boolean;
  isFamilyFriendly: boolean;
  description: string;
  descriptionHtml: string;
  tabs: string[];
  tags?: string[];
  latestVideos: VideoItem[];
  relatedChannels: ChannelItem[];
  channelHandle?: string;
}

export interface ChannelVideosResponse {
  videos: VideoItem[];
  continuation?: string;
}

export interface ChannelPlaylistsResponse {
  playlists: PlaylistItem[];
  continuation?: string;
}

export interface CommunityPost {
  attachment?: {
    type: string;
    imageThumbnails?: Thumbnail[];
    images?: Thumbnail[][];
    videoId?: string;
    title?: string;
    choices?: string[];
    totalVotes?: number;
    [k: string]: unknown;
  };
  author: string;
  authorId: string;
  authorThumbnails: Thumbnail[];
  authorIsChannelOwner?: boolean;
  commentId: string;
  content: string;
  contentHtml: string;
  likeCount: number;
  publishedText: string;
  replyCount?: number;
}

export interface CommunityResponse {
  authorId: string;
  comments: CommunityPost[];
  continuation?: string;
}

export interface PlaylistDetails {
  type: 'playlist' | 'invidiousPlaylist';
  title: string;
  playlistId: string;
  playlistThumbnail?: string;
  author: string;
  authorId?: string;
  authorUrl?: string;
  authorThumbnails?: Thumbnail[];
  description: string;
  descriptionHtml?: string;
  videoCount: number;
  viewCount: number;
  updated: number;
  isListed?: boolean;
  privacy?: 'public' | 'unlisted' | 'private';
  videos: VideoItem[];
}

export interface MixDetails {
  title: string;
  mixId: string;
  videos: VideoItem[];
}

export interface AuthPlaylist {
  type: 'invidiousPlaylist';
  title: string;
  playlistId: string;
  author: string;
  description: string;
  videoCount: number;
  updated: number;
  isListed: boolean;
  privacy?: string;
  videos: VideoItem[];
}

export interface AuthSubscription {
  author: string;
  authorId: string;
}

export interface SponsorSegment {
  category: string;
  actionType: 'skip' | 'mute' | 'poi' | 'full';
  segment: [number, number];
  UUID: string;
  videoDuration: number;
}

export interface Chapter {
  start: number;
  end: number;
  title: string;
}
